version: '3.8'


services:
  ms_app:
    container_name: ms_app
    build: .
    ports:
    - 8000:5000
    volumes:
    - ./:/ms
    environment:
    - FLASK_ENV=development
    depends_on:
    - ms_db
    networks:
    - msNet

  ms_db:
    container_name: ms_db
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - msAppVol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-ms_app}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
    - msNet

volumes:
  msAppVol:
    driver: local

networks:
  msNet:
    driver: bridge
